// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_polestar_naosdk_api_external.djinni

#import <Foundation/Foundation.h>

/**
 *--objc-type-prefix DB
 * Error codes
 */
typedef NS_ENUM(NSInteger, DBNAOERRORCODE)
{
    /** Invalid API key : inconsistent key accross services or key does not match PDB: check for typo in your key, check your site details on NAO Cloud and contact Pole Star Team. */
    DBNAOERRORCODE_INVALID_API_KEY,
    /** Problem occured during a service instantiation / termination */
    DBNAOERRORCODE_SERVICE_LIFECYCLE,
    /** Unable to synchronize data for your site: problem with the connection or missing inputs */
    DBNAOERRORCODE_DATA_SYNCHRO,
    /** Unsupported OS */
    DBNAOERRORCODE_UNSUPPORTED_OS,
    /** for Pole Star use, you should not see those. */
    DBNAOERRORCODE_INTERNAL_ERROR,
    /** generic error code */
    DBNAOERRORCODE_GENERIC_ERROR,
};
