// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_polestar_naosdk_api_external.djinni

#import <Foundation/Foundation.h>

/** Geofencing alert rule types */
typedef NS_ENUM(NSInteger, DBTALERTRULE)
{
    /** getting near a beacon */
    DBTALERTRULE_NEARRULE,
    /** moving away from a beacon */
    DBTALERTRULE_LEAVINGNEARRULE,
    /** entering beacon proximity */
    DBTALERTRULE_ENTERRULE,
    /** leaving beacon proximity */
    DBTALERTRULE_EXITRULE,
    /** entering a geofence polygon */
    DBTALERTRULE_ENTERGEOFENCERULE,
    /** exiting a geofence polygon */
    DBTALERTRULE_EXITGEOFENCERULE,
    /** being inside a geofence polygon */
    DBTALERTRULE_ISINSIDEGEOFENCERULE,
};
