// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_polestar_naosdk_api_external.djinni

#import <Foundation/Foundation.h>

/**
 *--objc-type-prefix DB
 * NAO Location service status
 */
typedef NS_ENUM(NSInteger, DBTNAOFIXSTATUS)
{
    /** A critical error has occurred: location is not available; details about the error are returned by onError callback. */
    DBTNAOFIXSTATUS_NAO_OUT_OF_SERVICE,
    /** Location is unavailable for lack of sensor input: sensors could have been turned off or device might be going off-site. */
    DBTNAOFIXSTATUS_NAO_TEMPORARY_UNAVAILABLE,
    /** Location fixes are being produced at a normal rate. */
    DBTNAOFIXSTATUS_NAO_FIX_AVAILABLE,
    /** Location is unavailable as device is off-site. */
    DBTNAOFIXSTATUS_NAO_FIX_UNAVAILABLE,
};
